#!/bin/bash

# this script installs ContextStorage following SetupHelper rules (https://github.com/kwindrem/SetupHelper)
#
# this script will accept the following commands on the command line:
#	setup install
#	setup uninstall

packageLogFile="/var/log/ContextStorage/current"

#### following lines incorporate SetupHelper utilities into this script
# Refer to the SetupHelper ReadMe file for details.

source "/data/SetupHelper/CommonResources"

#### end of lines to include SetupHelper

# GitHub account info - fill in as appropriate
# to include this package in SetupHelper automatic updates
packageGitHubUser="thomasinaz41213"
packageGitHubBranch="main"

restartSystemCalc=false

#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
	echo
	echo "Enabling Context Storage in Node Red"
	echo
	standardActionPrompt
fi

#### here to do the actual work

if [ $scriptAction == 'INSTALL' ] ; then
	logMessage "++ Installing ContextStorage"

    
	installService $packageName

	updateActiveFile /usr/lib/node_modules/node-red/venus-settings.js

	##

	logMessage "++ $packageName installed"
fi

# #### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    logMessage "++ Uninstalling ContextStorage"

	
	restoreActiveFile /usr/lib/node_modules/node-red/venus-settings.js
	
	
	##
	
	removeService $packageName
	restartSystemCalc=false
		
	logMessage "++ $packageName uninstalled"
fi



if $filesUpdated ; then
    ##
    ## Reboot or restart the services
    ##
    svc -d /service/node-red-venus ; svc -u /service/node-red-venus
    restartGui=false
fi

if $restartSystemCalc ; then
	logMessage "restarting systemcalc"
	svc -t /service/dbus-systemcalc-py
fi

# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript
